name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    needs: ["run-windows-commands"]
    steps:
    - uses: actions/checkout@v1
    - uses: ./action-a
      with:
        MY_NAME: "Mona"
  run-windows-commands:
    name: windows 
    runs-on: windows-latest
    steps:
      - name: Dictory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
