name: A workflow for my Hello World file
# on: push
on: 
  workflow_dispatch:
  pull_request:
    types:
      - opened
  push:
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./action-a
      with:
        MY_NAME: "Mona"
