name: A workflow for my Hello World file
on: [push]

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    needs: ["run-windows-commands"]
    steps:
    - uses: actions/checkout@v1
    - uses: ./action-a
      with:
        MY_NAME: "Mona"
  run-github-action:
    name: invoke public actions
    runs-on: ubuntun-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: list
        run: |
          pwd
          ls
      - uses: actions/hello-world-javascript-actions@v1
        name: simple JS action
        id: greet
        with:
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
  run-windows-commands:
    name: windows 
    runs-on: windows-latest
    steps:
      - name: Dictory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
